# Generated by Django 3.1.5 on 2021-02-14 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('countrycode', models.CharField(max_length=100)),
                ('price', models.CharField(default='0', max_length=100)),
                ('point_q', models.CharField(default='0', max_length=100)),
                ('day_lowest', models.CharField(default='0', max_length=100)),
                ('day_highest', models.CharField(default='0', max_length=100)),
                ('p_e', models.CharField(default='0', max_length=100)),
                ('market_cap', models.CharField(default='0', max_length=100)),
                ('public_float', models.CharField(default='0', max_length=100)),
                ('eps', models.CharField(default='0', max_length=100)),
                ('dividend', models.CharField(default='0', max_length=100)),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Associate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmarket.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
