# Generated by Django 3.2.7 on 2021-09-26 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0003_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='is_favorite',
        ),
    ]
