# Generated by Django 3.2.7 on 2021-09-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0004_remove_stock_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='point_q',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
