# Generated by Django 3.2.7 on 2021-09-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0013_alter_stock_p_e'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='p_e',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
