# Generated by Django 3.2.7 on 2021-09-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0015_alter_stock_eps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='dividend',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
