# Generated by Django 3.2.7 on 2021-09-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0016_alter_stock_dividend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='dividend',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
